# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Utk-terraform-azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:
- task: HelmInstaller@0
  inputs:
    helmVersion: 'latest'
    installKubectl: true

- script: |
    helm  ./devops/empwebapp/
    mkdir -p $(Build.ArtifactStagingDirectory)/charts
    mv *.tgz $(Build.ArtifactStagingDirectory)/charts/
  displayName: 'Package Helm chart'


- publish: $(Build.ArtifactStagingDirectory)/charts
  artifact: helm-charts
  displayName: 'Publish Helm charts'