name: AZURE Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up date tag
        id: vars
        run: echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: utkarshpathakacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_SECRET }}

      - name: Build and push backend Docker image
        run: |
          cd backend
          docker build -t utkarshpathakacr.azurecr.io/backend:${{ env.IMAGE_TAG }} .
          docker push utkarshpathakacr.azurecr.io/backend:${{ env.IMAGE_TAG }}

      - name: Build and push database Docker image
        run: |
          cd Database
          docker build -t utkarshpathakacr.azurecr.io/database_g:${{ env.IMAGE_TAG }} .
          docker push utkarshpathakacr.azurecr.io/database_g:${{ env.IMAGE_TAG }}

      - name: Build and push frontend Docker image
        run: |
          cd frontend
          docker build -t utkarshpathakacr.azurecr.io/frontend:${{ env.IMAGE_TAG }} .
          docker push utkarshpathakacr.azurecr.io/frontend:${{ env.IMAGE_TAG }}
