name: Docker Build and Push

on:
  push:
    branches: 
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      
      - name: Build and push backend Docker image
        run: |
          cd backend
          echo "${{ secrets.DOCKERPW }}" | docker login --u "utkarshpathak26" --password-stdin
          docker build -t utkarshpathak26/backend .
          docker push utkarshpathak26/backend

      - name: Build and push database Docker image
        run: |
          cd Database
          echo "${{ secrets.DOCKERPW }}" | docker login --u "utkarshpathak26" --password-stdin
          docker build -t utkarshpathak26/database_g .
          docker push utkarshpathak26/database_g
          
      - name: Build and push backend Docker image
        run: |
          cd backend
          echo "${{ secrets.DOCKERPW }}" | docker login --u "utkarshpathak26" --password-stdin
          docker build -t utkarshpathak26/frontend .
          docker push utkarshpathak26/frontend
